name: Checkmarx Scan
# test2 FF OFF and License OFF
on: [push,pull_request,workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: cx_liad_levy_pm
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --scan-types sast,api-security
